### PR TITLE
Change rtd method to pip

### PR DESCRIPTION
**Pull request by jbusecke**
The version is not properly generated for the docs. Switching the install method to pip.

### CODE REVIEW

**Comment by jbusecke** [comment]
Hmmm that doesnt fix it. It seems from the [logs](https://readthedocs.org/api/v2/build/13476198.txt) that pip is not invoked at all?

**Comment by jbusecke** [comment]
I just updated the syntax to v2 of RTD and required the newer version (I was not aware this was necessary), but now the build takes forever

**Comment by jbusecke** [comment]
I have now completely switched the requirements over to the pip install in `setup.cfg`. The builds are backed up now, but hopefully this will speed up new builds.

**Comment by jbusecke** [comment]
Man this is aggrevating... its just sitting there...

**Comment by lukegre** [comment]
Picking this up from the [jbusecke/cookiecutter-science-project#36](https://github.com/jbusecke/cookiecutter-science-project/pull/36). Just had a look through RTD log. `cartopy` seems to be a snag-point.  I've never had much luck installing `cartopy` with pip. One of the reasons I've stuck with `conda`. 

I saw it's a requirement for `xgcm`, but didn't see it used in that repo. Perhaps this is a dependency that can be removed from `xgcm`?

**Comment by jbusecke** [comment]
I have asked to activate mamba building and it has been activated. I'll see how that goes.

**Pull request closed without merging**
