### PR TITLE
Cloud tests gh actions

### PR DESCRIPTION
**Pull request by jbusecke**
After switching to gh actions in #61 , I am trying again to get the high level tests with the google cloud data to work.

### CODE REVIEW

**Comment by jbusecke** [comment]
I am not quite sure I understand these failures. I have currently restricted the test module to run for a single model (`CanESM5`) and only the most simple of the tests. I was able to run this test from my local machine successfully, but it seems that when I run this from within GHA, the `.zmetadata` file cannot be found. Is this a permission issue of sorts?

cc'ing @charlesbluca @rabernat here, since you folks know much more about GHA and cloud stuff in general

**Comment by jbusecke** [comment]
It seems there is a general problem with accessing the data. I have deactivated the `consolidated` option and it still says that group is not found. Wondering if I need to add some special token or similar to enable GHA to 'see' the cloud data.

**Comment by charlesbluca** [comment]
I think the problem is at:

```
ds_raw = xr.open_zarr(cat.df["zstore"][0], **zarr_kwargs)
```

Xarray is getting a string for the path of the Zarr dataset in cloud, when [it's expecting a mutable mapping](https://xarray.pydata.org/en/stable/io.html#cloud-storage-buckets) created from that path using either `gcsfs` or `fsspec`. This should be circumvented if you do something like:

```
mm = fsspec.get_mapper(cat.df["zstore"][0]) # think you can pass in storage options here as well?
ds_raw = xr.open_zarr(mm, **zarr_kwargs)
```

**Comment by jbusecke** [comment]
Thanks a lot for looking into this @charlesbluca. Ill check out if this works now.

**Comment by charlesbluca** [comment]
After checking it out on my own end, I _think_ the issue might be that passing a `gs://` path directly to Xarray's `open_zarr` method relies on `gcloud` rather than `gcsfs` - at least, that's my assumption since that's the main difference between my local machine and the workflow in terms of dependencies.

I'll try it out myself, but I think adding a step to set up `gcloud` could also resolve the issue.

**Comment by jbusecke** [comment]
It worked! 
4ppfee

**Comment by charlesbluca** [comment]
😂 glad I was able to help!

This does showcase some interesting behavior on Xarray's part though - I would've assumed it would rely on `gcsfs` or `fsspec` if they were in the environment before falling back to `gcloud`.

**Comment by jbusecke** [comment]
Do you think this is worth raising an issue over there?

**Comment by charlesbluca** [comment]
It might be - I'll check out what's going on with the actual `open_zarr` function first to see if there's something I'm missing.

**Comment by jbusecke** [comment]
I doubt that I will be of much help, but let me know if there is something I can do on this end to help.

**Comment by charlesbluca** [comment]
Found the answer - it has to do with the bump from [0.16.1](https://github.com/pydata/xarray/blob/633187e32be3559ee4989b5049449d51372a1178/xarray/backends/zarr.py#L498) to [0.16.2](https://github.com/pydata/xarray/blob/cc53a77ff0c8aaf8686f0b0bd7f75985b74e2054/xarray/backends/zarr.py#L555) in Xarray.

On 0.16.1 and earlier, the path string is passed directly to Xarray's `ZarrStore` constructor, and eventually Zarr's `open_group`, where it works fine because Zarr is able to open datasets with the path string alone.

On 0.16.2 and onward, the path string is passed into `xarray.open_dataset(...engine="zarr")`, and before being passed on to Zarr's `open_group`, it is normalized - essentially treated as a path in your local file system. Thus the Zarr error saying it can't find the dataset in your local file system.

Essentially, Xarray used to unintentionally support opening Zarr datasets in the cloud with only the path string (though it wasn't necessarily documented), and now it **only** supports mutable mappings for those cases.

**Comment by dcherian** [comment]
> On 0.16.2 and onward, the path string is passed into xarray.open_dataset(...engine="zarr"), and before being passed on to Zarr's open_group, it is normalized - essentially treated as a path in your local file system. Thus the Zarr error saying it can't find the dataset in your local file system.

Can you open an issue please?

**Comment by charlesbluca** [comment]
Done! @dcherian:

- [Non-HTTPS remote URLs no longer work as input for open_zarr](https://github.com/pydata/xarray/issues/4691)

**Pull request merged**
