### PR TITLE
Added naming for atmospheric/regridded-ocean files

### PR DESCRIPTION
**Pull request by jbusecke**

### CODE REVIEW

**Comment by jbusecke** [comment]
@aaronspring, this should enable most of the atmospheric data to be preprocessed. Would appreciate if you could give it a spin, since I am not that familiar with the data. If there are inconsistencies beyond the lon lat convention (levels, units etc), please let me know.

**Comment by aaronspring** [comment]
just using `preprocess=combined_preprocessing` works.

I am not sure whether the dimension renaming from `lon, lat` to `x,y` is needed for atmospheric data, but lon, lat is still there as coord. and it plots nicely.

so `plev` is the height dim in atmosphere. basically what is `lev` is for the ocean.
looks quite homogenous. all in pascal units, all 19 levels, probably all prescribed by CMIP6. I see potential problems here if a model doesnt stick to `positive=down` and then the scale would need to be inverted, but so far looks good. 
```
for k in dset_dict.keys():
    print(k,dset_dict[k].plev.attrs)
CMIP.CNRM-CERFACS.CNRM-ESM2-1.piControl.Amon.gr {'name': 'plev', 'standard_name': 'air_pressure', 'long_name': 'pressure', 'units': 'Pa', 'positive': 'down'}
CMIP.NOAA-GFDL.GFDL-ESM4.piControl.Amon.gr1 {'long_name': 'pressure', 'units': 'Pa', 'axis': 'Z', 'positive': 'down', 'standard_name': 'air_pressure', 'description': 'There are 19  requested levels. If the upper levels are above the model top they should be omitted.'}
CMIP.NCAR.CESM2-WACCM.piControl.Amon.gn {'axis': 'Z', 'positive': 'down', 'requested': '100000. 92500. 85000. 70000. 60000. 50000. 40000. 30000. 25000. 20000. 15000. 10000. 7000. 5000. 3000. 2000. 1000. 500. 100.', 'standard_name': 'air_pressure', 'title': 'pressure', 'type': 'double', 'units': 'Pa'}
CMIP.NCAR.CESM2.piControl.Amon.gn {'axis': 'Z', 'positive': 'down', 'requested': '100000. 92500. 85000. 70000. 60000. 50000. 40000. 30000. 25000. 20000. 15000. 10000. 7000. 5000. 3000. 2000. 1000. 500. 100.', 'standard_name': 'air_pressure', 'title': 'pressure', 'type': 'double', 'units': 'Pa'}
CMIP.MRI.MRI-ESM2-0.piControl.Amon.gn {'units': 'Pa', 'axis': 'Z', 'positive': 'down', 'long_name': 'pressure', 'standard_name': 'air_pressure'}
```
so this is just a few models in piControl and co2.

**Comment by aaronspring** [comment]
so here is something that breaks:
`psl` `piControl` `FGOALS-g3`
just opening this file directly with xr.open_dataset().coords:
```
Coordinates:
    time     object 0730-04-16 00:00:00
  * lat      (lat) float64 -90.0 -84.82 -80.72 -77.22 ... 77.22 80.72 84.82 90.0
  * lon      (lon) float64 0.0 2.0 4.0 6.0 8.0 ... 350.0 352.0 354.0 356.0 358.0
```
which looks good to me, or at least like the datasets
```
/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/cmip6_preprocessing/preprocessing.py in combined_preprocessing(ds)
    866         ds = promote_empty_dims(ds)
    867         # broadcast lon/lat
--> 868         ds = broadcast_lonlat(ds)
    869         # replace x,y with nominal lon,lat
    870         ds = replace_x_y_nominal_lat_lon(ds)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/cmip6_preprocessing/preprocessing.py in broadcast_lonlat(ds, verbose)
    794 
    795     if len(ds['lon'].dims) < 2:
--> 796         ds.coords["lon"] = ds["lon"] * xr.ones_like(ds["lat"])
    797     if len(ds['lat'].dims) < 2:
    798         ds.coords["lat"] = xr.ones_like(ds["lon"]) * ds["lat"]

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/coordinates.py in __setitem__(self, key, value)
     38 
     39     def __setitem__(self, key: Hashable, value: Any) -> None:
---> 40         self.update({key: value})
     41 
     42     @property

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/coordinates.py in update(self, other)
    114         other_vars = getattr(other, "variables", other)
    115         coords, indexes = merge_coords(
--> 116             [self.variables, other_vars], priority_arg=1, indexes=self.indexes
    117         )
    118         self._update_coords(coords, indexes)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/merge.py in merge_coords(objects, compat, join, priority_arg, indexes, fill_value)
    452         coerced, join=join, copy=False, indexes=indexes, fill_value=fill_value
    453     )
--> 454     collected = collect_variables_and_indexes(aligned)
    455     prioritized = _get_priority_vars_and_indexes(aligned, priority_arg, compat=compat)
    456     variables, out_indexes = merge_collected(collected, prioritized, compat=compat)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/merge.py in collect_variables_and_indexes(list_of_mappings)
    275                 append_all(coords, indexes)
    276 
--> 277             variable = as_variable(variable, name=name)
    278             if variable.dims == (name,):
    279                 variable = variable.to_index_variable()

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/variable.py in as_variable(obj, name)
    141                 "dimensions %r. xarray disallows such variables because they "
    142                 "conflict with the coordinates used to label "
--> 143                 "dimensions." % (name, obj.dims)
    144             )
    145         obj = obj.to_index_variable()

MissingDimensionsError: 'lon' has more than 1-dimension and the same name as one of its dimensions ('lon', 'lat'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.
```

**Comment by jbusecke** [comment]
That is odd. Ill look into that in a bit. Ill transfer it to a new issue.

**Comment by jbusecke** [comment]
Ah sorry. I previously removed that particular model. Ill put together a new PR to fix that.

**Comment by aaronspring** [comment]
I now ran a better example with `zg` which is geopothential height and holds dims lon,lat,plev:
```
col_url = "/home/mpim/m300524/intake-esm-datastore/catalogs/mistral-cmip6.json"
col = intake.open_esm_datastore(col_url)
variable_id='zg'
# not on the ocean grid but atmospheric grid
query = dict(experiment_id="piControl",table_id='Amon',variable_id=variable_id)
cat = col.search(**query)
cat_model = cat.search(source_id=model)
    ds = xr.open_mfdataset(cat_model.df.iloc[0].path)[variable_id]
    print(ds.coords)
    # print(ds.plev.attrs)
    # print(ds.plev.values)
    # ds=ds.isel(time=3).isel(plev=2)
    # ds.plot()
    # plt.show()
    try:
        dset_dict = cat_model.to_dataset_dict(cdf_kwargs=cdf_kwargs, preprocess=combined_preprocessing)
    except Exception as e:
        print(f'{model} fails due to {e} ')
/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/merge_util.py in _open_asset(path, data_format, zarr_kwargs, cdf_kwargs, preprocess)
    200     else:
    201         logger.info(f'Applying pre-processing with {preprocess.__name__} function')
--> 202         return preprocess(ds)
    203 
    204 

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/cmip6_preprocessing/preprocessing.py in combined_preprocessing(ds)
    866         ds = promote_empty_dims(ds)
    867         # broadcast lon/lat
--> 868         ds = broadcast_lonlat(ds)
    869         # replace x,y with nominal lon,lat
    870         ds = replace_x_y_nominal_lat_lon(ds)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/cmip6_preprocessing/preprocessing.py in broadcast_lonlat(ds, verbose)
    794 
    795     if len(ds['lon'].dims) < 2:
--> 796         ds.coords["lon"] = ds["lon"] * xr.ones_like(ds["lat"])
    797     if len(ds['lat'].dims) < 2:
    798         ds.coords["lat"] = xr.ones_like(ds["lon"]) * ds["lat"]

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/coordinates.py in __setitem__(self, key, value)
     38 
     39     def __setitem__(self, key: Hashable, value: Any) -> None:
---> 40         self.update({key: value})
     41 
     42     @property

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/coordinates.py in update(self, other)
    114         other_vars = getattr(other, "variables", other)
    115         coords, indexes = merge_coords(
--> 116             [self.variables, other_vars], priority_arg=1, indexes=self.indexes
    117         )
    118         self._update_coords(coords, indexes)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/merge.py in merge_coords(objects, compat, join, priority_arg, indexes, fill_value)
    452         coerced, join=join, copy=False, indexes=indexes, fill_value=fill_value
    453     )
--> 454     collected = collect_variables_and_indexes(aligned)
    455     prioritized = _get_priority_vars_and_indexes(aligned, priority_arg, compat=compat)
    456     variables, out_indexes = merge_collected(collected, prioritized, compat=compat)

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/merge.py in collect_variables_and_indexes(list_of_mappings)
    275                 append_all(coords, indexes)
    276 
--> 277             variable = as_variable(variable, name=name)
    278             if variable.dims == (name,):
    279                 variable = variable.to_index_variable()

/work/mh0727/m300524/miniconda3/envs/pymistral/lib/python3.7/site-packages/xarray/core/variable.py in as_variable(obj, name)
    141                 "dimensions %r. xarray disallows such variables because they "
    142                 "conflict with the coordinates used to label "
--> 143                 "dimensions." % (name, obj.dims)
    144             )
    145         obj = obj.to_index_variable()

MissingDimensionsError: 'lon' has more than 1-dimension and the same name as one of its dimensions ('lon', 'lat'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.
```
for models ... it get error:
- FGOALS-g3 fails due to 'lon' has more than 1-dimension and the same name as one of its dimensions ('lon', 'lat'). xarray disallows such variables because they conflict with the coordinates used to label dimensions. 

all other models pass 👍

**Pull request merged**
