### PR TITLE
Expand Full Archive sweep

### PR DESCRIPTION
**Pull request by jbusecke**
#78 implemented a less frequently executed CI workflow, that should eventually sweep the full CMIP6 cloud archive (#77).

It works but I need to enter a lot more failcases manually, and this should be completed before we compare the current and new catalogs (see [here](https://github.com/jbusecke/cmip6_preprocessing/issues/77#issuecomment-770290928)) to detect differences.

To facilitate this I have implemented a bit more convenient matching for failcase identifiers, supporting wildcards and lists to reduce the manual entry work.

### CODE REVIEW

**Comment by jbusecke** [comment]
Ugh this is absolutely tedious. I cant figure out how to give a small summary of the failure in the last section (this works for me locally..)
E.g. something like this: 
```
========================= short test summary info ==========================
SKIPPED [1] test_example.py:22: skipping this test
XFAIL test_example.py::test_xfail
  reason: xfailing this test
XPASS test_example.py::test_xpass always xfail
ERROR test_example.py::test_error - assert 0
FAILED test_example.py::test_fail - assert 0

```
[source](https://docs.pytest.org/en/latest/usage.html#detailed-summary-report)

I cant make the CI output give me this, so it is really annoying to figure out which failures are xpass or actual failures...

**Comment by dcherian** [comment]
yo you should be able to ssh into a container somehow and run pytest on a command line. Might save some sanity ;)

**Comment by jbusecke** [comment]
Oh yeah that would be awesome. How would I go about that?

**Comment by jbusecke** [comment]
I found [this](https://github.com/marketplace/actions/debugging-with-ssh). Ill try it now.

**Comment by jbusecke** [comment]
Actually what I should have done is to debug this on the pangeo deployment, not my local machine 🤦‍♂️

**Pull request merged**
