### PR TITLE
Activate single rerun with 10s delay for flakey tests.

### PR DESCRIPTION
**Pull request by jbusecke**

### CODE REVIEW

**Comment by jbusecke** [comment]
I tried to implement retries to exclude some sort of cloud problems, but that did not solve the problem.  It also seems that the tests now fail for another single model (`FGOALS-g3-thetao-historical-gn`), this is a different one than @andersy005 noticed earlier in https://github.com/intake/intake-esm/issues/305 (`CESM2-thetao-ssp585-gn`). Are these files currently updated/rewritten by any chance @charlesbluca @naomi-henderson?

**Comment by charlesbluca** [comment]
I don't have much knowledge of what specific CMIP6 models are being updated - that's more of Naomi's territory.

Do you have the URL this model corresponds to (i.e. `gs://...`)? I could check the logs of my syncing workflow to see if there have been any major changes to it in the past few days.

**Comment by jbusecke** [comment]
These are the stores for the current failure:
```
['gs://cmip6/CMIP/CAS/FGOALS-g3/historical/r1i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/CMIP/CAS/FGOALS-g3/historical/r2i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/CMIP/CAS/FGOALS-g3/historical/r3i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/CMIP/CAS/FGOALS-g3/historical/r4i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/CMIP/CAS/FGOALS-g3/historical/r5i1p1f1/Omon/thetao/gn/']
```

And these are the ones for the previous failure (would be curious if that one was recently touched/modified in any way too):
```
['gs://cmip6/ScenarioMIP/NCAR/CESM2/ssp585/r10i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/ScenarioMIP/NCAR/CESM2/ssp585/r11i1p1f1/Omon/thetao/gn/',
 'gs://cmip6/ScenarioMIP/NCAR/CESM2/ssp585/r4i1p1f1/Omon/thetao/gn/']
```

Thanks for checking on this @charlesbluca

**Comment by charlesbluca** [comment]
Skimming through, it looks like the affected model was altered at some point 18-24 hours ago; some of the relevant run logs here (they're pretty dense so but searching for `FGOALS` should help find the affected files):

- [r2i1p1f1 is rewritten](https://github.com/pangeo-cmip6/sync/runs/1586260013?check_suite_focus=true)
- [r3i1p1f1, r4i1p1f1, r5i1p1f1 are rewritten](https://github.com/pangeo-cmip6/sync/runs/1585384561?check_suite_focus=true)

I haven't yet found logs recording rewrites for r1i1p1f1, but I imagine this would have happened at a similar time. Still not sure what the cause for this update was, but if Naomi doesn't chime in, I could check out the [Errata](https://errata.es-doc.org/static/index.html) to see if this is related to some issue being resolved.

**Comment by jbusecke** [comment]
Thanks for checking. I think this strengthens my suspicion, that something was changed in the original store. I believe one of the members would suffice to cause those errors.
For now, I guess Ill add these to the failing models and see how this develops and if Naomi has some further insight.

**Comment by jbusecke** [comment]
Errata shows no entry for that particular model, just FYI.

**Comment by naomi-henderson** [comment]
@jbusecke , etc.  Yes, FGOALS-g3/historical/r1i1p1f1/Omon/thetao/gn/ was added on Dec 19 and the other ensemble members on Dec 20.  They are new datasets and did not exist in the cloud prior to Dec 19.  There were other variables available for this ensemble member, but not thetao

**Comment by naomi-henderson** [comment]
.. and the CESM2-thetao-ssp585-gn datasets - r1i1p1f1 and r2i1p1f1 are in GC - but marked as having a 'severe' issue - so are excluded from the standard catalog.  The r4 member was uploaded Aug 17, 2020, but the r10 and r11 ensemble members were just uploaded on Nov 22, 2020.  

Flakey behaviour would certainly result if any of these was being read while it was being uploaded ...  

Anything I can do to help at this point?

**Comment by jbusecke** [comment]
Thanks @naomi-henderson. I am curious about this:

>but marked as having a 'severe' issue
Are datasets with 'severe issues' catalogued somewhere, so I can automatically exclude those?

**Comment by naomi-henderson** [comment]
@jbusecke, there is not a separate catalog for 'severe issues' - instead we keep two catalogs.  The standard catalog is:
`cmip6-zarr-consolidated-stores.csv` , which is the same as `pangeo-cmip6.csv` in the `intake-esm` .json file.

The complete catalog includes all datasets in the google cloud (with additional columns 'status', 'severity', 'issue_url') is:
`cmip6-zarr-consolidated-stores-noQC.csv` - the 'no Quality Control' version

So, if you use the standard catalog, you should not see the datasets with 'severe issues' (unless, of course, a new issue has recently been added to ES-DOC)

**Comment by jbusecke** [comment]
Ah thank you for clarifying, that is very helpful info. I think I need to find a way to not fail my tests each time a single dataset fails and instead have a log or sorts that only raises a fatal error if some dataset continuously produces errors. This is not really 'flaky' as initially thought (which would be more of an intermittent connection error or the like). This is clearly not nearly where I want it to be, but Ill keep on working on it.

**Comment by jbusecke** [comment]
This works now, but the rerun parameter did not actually improve the situation. Ill leave it in and merge anyways.

**Pull request merged**
