### PR TITLE
Fix python versions in dev/cloud ci

### LINKED ISSUE #230: Upstream dev CI failing during mamba stage
The [upstream build](https://github.com/jbusecke/cmip6_preprocessing/runs/6460713102?check_suite_focus=true) is failing, and I am not quite sure I understand why. 

It seems that this happens during the environment setup step, not the testing itself, maybe this is some issue with the github actions themselves or mamba?
For now I will wait and see if this issue resolves itself, but I wanted to tag it here. Maybe someone has seen this happen before and has some tips.

### PR DESCRIPTION
**Pull request by jbusecke**
- [ ] Closes #230

### CODE REVIEW

**Comment by jbusecke** [comment]
The error in #230 is persisting here. Upon closer inspection it seems like it might be an issue with [pint-xarray](https://github.com/jbusecke/cmip6_preprocessing/runs/6489837784?check_suite_focus=true#step:5:1032)? @TomNicholas do you think that there is something going on upstream at pint-xarray?

**Comment by TomNicholas** [comment]
Which part of that error message makes you think it is a problem with pint-xarray? It seems to me that the last thing it attempts to install before failing is rasterio.

**Comment by jbusecke** [comment]
Oh I might have misread the error log (which is pretty confusing IMO). I based this on line [1022](https://github.com/jbusecke/cmip6_preprocessing/runs/6489837784?check_suite_focus=true#step:5:1032) and the error appearing below.

**Comment by mathause** [comment]
Seems to be an issue with python 3.10 + rasterio + pip: 

```bash
mamba create -n test_rasterio python=3.10 pip
mamba activate test_rasterio
pip install rasterio
```

The same works for python 3.9. Not sure if there is a rasterio issue already - maybe https://github.com/rasterio/rasterio/issues/2310 - it might work when installing rasterio with mamba/ conda.

---

Side note, cartopy is no longer a hard dependency of regionmask, and could potentially be removed from the upstream-dev packages (but I am of course not sure about the rest of your stack...)

https://github.com/jbusecke/cmip6_preprocessing/blob/7e75a548e24e87f447fbb4a5644bd84f7fc0b01f/ci/environment-upstream-dev.yml#L8

**Comment by jbusecke** [comment]
> installing rasterio with mamba/ conda.

Thats a good idea. Testing that now.

> Side note, cartopy is no longer a hard dependency of regionmask, and could potentially be removed from the upstream-dev packages (but I am of course not sure about the rest of your stack...)

Thanks for that update! I think for now I still need it, but I would be very keen to completely get rid of the masking via https://github.com/nvkelso/natural-earth-vector/issues/697. That way I could simply point users to the 'awesome regionmask package' 😎 and could get rid of some dependencies here!

**Comment by jbusecke** [comment]
Some of the code here requires the now deprecated 'extrapolate' padding option in xgcm. I have pinned an older version for now, but will raise a separate issue to discuss how we can integrate the latest xgcm developments.

**Comment by jbusecke** [comment]
Seems like the remaining issues are related to https://github.com/pangeo-data/xESMF/issues/170. I guess I have the option to either include sparse+numba in my env files or wait for a new release of xesmf here.

**Comment by jbusecke** [comment]
Yep @mathause you were right. Rerunning the test eliminated the error. Thanks for the quick reply!

**Pull request merged**
