### PR TITLE
More tests and xr 0.15.1 fixes

### PR DESCRIPTION
**Pull request by jbusecke**
This PR adds:
- a bunch of formatting correction (I used black to format the code)
- Many more tests for the `preprocessing.py` module
- Ci environment for python 3.8
- Another fix to ensure compatibility with the new xarray version (0.15.1)

### CODE REVIEW

**Comment by aaronspring** [comment]
pre-commit would be nice to not get these string normalisation changes everywhere.

**Comment by jbusecke** [comment]
Agreed. This package was not set up very carefully from the beginning. There are a bunch of features we need. Ill try to add them in more atomic PRs instead of lumping things together.

**Comment by jbusecke** [comment]
@aaronspring are you ok with merging this otherwise? I would like to get rid of the failing main build.

**Comment by jbusecke** [comment]
Good thing I had the tests. Something failed in the assign statements. Ill leave them as I had them to ensure correctness. Merging as soon as CI passes.

**Pull request merged**
