### PR TITLE
New module to calculate and remove control run drift

### LINKED ISSUE #123: Adding detrending/drift removal functionality
I have developed quite a bit of logic to remove control run drift from CMIP6 models for my recent [OMZ paper](https://www.essoar.org/doi/10.1002/essoar.10507050.1), and would like to refactor this into cmip6_preprocessing.

The logic I use has these basic steps:

- Use the metadata of every historical member (see #95 for further explanation of nomenclature) to get the branch time in the parent `piControl` run `branch_time_parent`.
- Select a 250 year time period starting at `branch_time_parent`, and calculate a linear slope at every `x`, `y`, and `lev` position. Save that output
- Remove this trend from historical and forced runs by assuming an intercept of 0 at time `1850-01-01` (the time when the historical forcing starts). 

I will migrate this functionality here (and would then welcome feedback), but I wanted to discuss the API first.

First of all I was wondering about how to call the module (which I would create for this purpose): 
- `cmip6_preprocessing/drift_correction`
- `cmip6_preprocessing/time_tools` (this could more general time related functionality like #64, which is also needed for the above tools)
- `cmip6_preprocessing/detrending` (seems a bit ambiguous to me?)
Not super stoked about these yet. Any ideas?

For the API I would imagine something along the lines of:
```python
from cmip6_preprocessing.cool_modulename import sel_from_branch, detrend

ds = ...
ds_control ... # matching control run (can be inferred and matched from attributes similar as in #120)

matching_control = sel_from_branch(ds, ds_control, yrs=250)
slope = matching_control.polyfit(dim='time', deg=1)
# in a realistic workflow I would save these files out (they are relatively small) and load them back for analysis
ds_nodrift = detrend(ds, slope, start_date = '1850-01-01`)
```

Any thoughts?

cc @MackenzieBlanusa

### PR DESCRIPTION
**Pull request by jbusecke**
- [x] Closes #123
- [ ] Finish Documentation
    - [x] Implement Rechunker
    - [ ] Debug the trend calculation method (something in polyfit is weird -> raise issue over at xarray)
- [x] Implement provenance information in the de-drifted data

### CODE REVIEW

**Comment by jbusecke** [comment]
Ok I have ported the basic functionality from my private OMZ project here, added some tests and docs. 

I think I still don't have the most intuitive naming for the functions (lots of changes between drift/trend etc). 

It would be helpful to get some more eyes on this, especially [on the new docs](https://cmip6-preprocessing--126.org.readthedocs.build/en/126/drift_removal.html) maybe @MackenzieBlanusa  @sditkovsky could take a look over the example. Happy to make name changes!

**Comment by jbusecke** [comment]
My thinking for terminology was: 
- `trend` general expression for a linear trend over a timeseries
- `drift` particularly the control run trend

But maybe you folks have a much better idea.

**Comment by sditkovsky** [comment]
> * `trend` general expression for a linear trend over a timeseries
> * `drift` particularly the control run trend

This makes sense to me. Could you even go further and say that a trend necessarily has drift removed? Might not be worth the effort, but you could have an attribute that flags whether a timeseries is 'de-drifted'. So that when you take the trend, it can check whether the drift has been removed already or not.

**Comment by MackenzieBlanusa** [comment]
> My thinking for terminology was:
> 
> * `trend` general expression for a linear trend over a timeseries
> * `drift` particularly the control run trend
> 
> But maybe you folks have a much better idea.

I was able to follow along pretty easily and was not confused by the naming. However, if you wanted to make the naming more consistent maybe you could rename `remove_trend` to `remove_drift` . Also, I think it would be worth including a section where you show how you rechunked the data or provide a link to the `rechunker` docs . It's not obvious to me what size to rechunk to, but I'm also still somewhat new to this.

**Comment by jbusecke** [comment]
Thank you both for the excellent suggestions!

I will try to modify the docs to include an example for rechunker now. 

@sditkovsky: I think that is a really important point. I am still thinking about how to implement this in practice. I think this attribute would have to be constructed from the `da_slope` array attributes in `remove_trend(da, da_slope, ref_date, check_mask=True)`. I imaging adding an attribute like 
```python
da_slope.attrs['drift_removed'] = 'linear_trend_CMIP.CCCma.CanESM5-CanOE.piControl.r1i1p2f1.Omon.thetao.gn_startdate_enddate'
```
This should then provide all the info needed to recreate the drift remove manually? Or can you think of another information needed?

**Comment by jbusecke** [comment]
Ill go ahead and merge this. There is some issue that seems to be related to the new indexing in the upstream xarray version. I'll try to deal with that over at https://github.com/jbusecke/xarrayutils/issues/96

**Pull request merged**
